<a href="https://colab.research.google.com/github/TheLordSaurabh/Credit-Card-Fraud-Detection-Model/blob/main/Credit_Card_Fraud_Detection_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credit Card Fraud Detection (via Logistic Regression) Project

SAURABH GUPTA

In [176]:
#Importing modules and dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [177]:
#The Dataset

#The Data Set used here is taken from Internet for Educational & Demonstration purpose only. The author of this project doesn't claim the ownership of this dataset. The complete ownership of this dataset belongs to the organisation which created this dataset.
#Dataset taken from : (https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud)

#Let's load the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/drive/MyDrive/Projects/Machine-Learning/Personal-Projects/Credit-Card-Fraud-Detection/Data/credit_card_data.csv')

In [178]:
#The first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [179]:
#The last 5 rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [180]:
# Important Informations about the Dataset
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [181]:
# Let's check the number of missing values in each column

credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [182]:
# Let's see the distribution of legit transaction and fraudulent transactions
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

This Dataset is highly unbalanced

So we need extra processing :

Let : 0 represent Normal Transaction and 1 represent Fraudulent Transaction

In [183]:
# Separating Data for Detailed Analysis
fraud = credit_card_data[credit_card_data.Class == 1]
legit = credit_card_data[credit_card_data.Class == 0]

print(legit.shape)
print()
print(fraud.shape)

(284315, 31)

(492, 31)

In [184]:
# Statistical Measures of the Legit Data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [185]:
# Statistical Measures of the Fraud Data
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [186]:
# Compare the values for both transactions
credit_card_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Let's deal the unbalanced data (high difference in the number of fraud and legit transac.)

We will Under-Sampling here

Let's take 400 random Fraudulent Transactions and 400 random Legit Transactions

In [187]:
legit_sample = legit.sample(n=400)

fraud_sample = fraud.sample(n=400)

Concatenating two dataframes (legit_sample and fraud_sample)

In [188]:
new_dataset = pd.concat([legit_sample,fraud_sample],axis = 0)

In [189]:
#first 5 rows of new_dataset

new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3292,2836.0,-1.129789,0.729794,1.290206,1.229443,-0.013296,0.516711,0.063175,0.802281,-0.657507,...,0.048136,-0.056744,-0.218672,-0.339359,0.428465,-0.123194,-0.044684,-0.043321,44.99,0
26880,34293.0,-0.386635,1.117792,-0.136068,1.063631,0.245458,-1.299016,0.608729,0.137348,-0.776017,...,0.218024,0.620260,0.095627,0.417920,-0.664147,-0.418591,0.318202,0.126036,19.00,0
110716,71941.0,-0.854743,1.409568,0.840793,-0.526831,0.598850,0.543826,0.072032,-1.436130,-0.533149,...,1.267949,-1.195668,0.018153,-1.059279,0.020160,0.148556,0.336041,0.113095,2.68,0
262673,160596.0,-0.512890,0.767378,-0.225148,-0.338568,0.538544,-0.792867,0.452572,0.221266,-0.248835,...,-0.209164,-0.734886,0.094828,-0.664417,-0.357572,0.261315,-0.242860,-0.039860,1.98,0
203424,134812.0,-2.025172,1.807092,0.708191,-0.333551,-1.431003,-0.019006,-1.272075,-1.321470,0.292009,...,2.761516,0.497732,0.181607,0.514103,-0.048922,-0.092722,0.148431,0.093342,24.48,0

In [190]:
#last 5 rows of new_dataset

new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
254395,156710.0,0.202402,1.176270,0.346379,2.882138,1.407133,-0.504355,1.438537,-0.395603,-1.555142,...,0.242560,0.841230,-0.370157,-0.026012,0.491954,0.234576,-0.279788,-0.331933,7.59,1
42473,41116.0,-3.600544,4.519047,-6.340884,6.214767,-5.829558,-2.478095,-9.938412,2.830086,-5.659162,...,2.263770,0.620749,-0.094069,0.536719,0.398142,0.008277,2.053524,0.835749,3.79,1
114271,73408.0,-2.869795,1.335667,-1.009530,1.693885,-0.741480,-0.796773,-2.614242,1.066636,-1.135497,...,0.528421,0.228027,-0.749298,-0.067179,0.215792,-0.453651,0.349191,0.198862,16.48,1
208651,137211.0,0.630579,1.183631,-5.066283,2.179903,-0.703376,-0.103614,-3.490350,1.094734,-0.717418,...,0.621622,0.043807,0.102711,-0.601505,0.127371,-0.163009,0.853792,0.356503,39.45,1
234633,148053.0,1.261324,2.726800,-5.435019,5.342759,1.447043,-1.442584,-0.898702,0.123062,-2.748496,...,0.209086,-0.425938,-0.154440,-0.018820,0.632234,0.192922,0.468181,0.280486,1.59,1

In [191]:
new_dataset['Class'].value_counts()

0    400
1    400
Name: Class, dtype: int64

In [192]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94132.2925,-0.016437,0.085929,0.12909,0.111170,0.041528,-0.098476,0.011572,0.049125,0.003131,...,0.007657,-0.006071,0.008307,0.001731,-0.044658,-0.000193,-0.008539,0.006959,0.016323,75.19755
1,80739.2675,-4.632724,3.579437,-6.87051,4.508195,-3.063326,-1.401905,-5.482128,0.639135,-2.550197,...,0.329723,0.725275,0.041624,-0.072025,-0.098928,0.016282,0.046300,0.156822,0.082787,111.45390

Splitting the data into features and targets

In [193]:
X = new_dataset.drop(columns = 'Class', axis = 1)
Y = new_dataset['Class']

In [194]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
3292      2836.0 -1.129789  0.729794  1.290206  1.229443 -0.013296  0.516711
26880    34293.0 -0.386635  1.117792 -0.136068  1.063631  0.245458 -1.299016
110716   71941.0 -0.854743  1.409568  0.840793 -0.526831  0.598850  0.543826
262673  160596.0 -0.512890  0.767378 -0.225148 -0.338568  0.538544 -0.792867
203424  134812.0 -2.025172  1.807092  0.708191 -0.333551 -1.431003 -0.019006
...          ...       ...       ...       ...       ...       ...       ...
254395  156710.0  0.202402  1.176270  0.346379  2.882138  1.407133 -0.504355
42473    41116.0 -3.600544  4.519047 -6.340884  6.214767 -5.829558 -2.478095
114271   73408.0 -2.869795  1.335667 -1.009530  1.693885 -0.741480 -0.796773
208651  137211.0  0.630579  1.183631 -5.066283  2.179903 -0.703376 -0.103614
234633  148053.0  1.261324  2.726800 -5.435019  5.342759  1.447043 -1.442584

              V7        V8        V9  ...       V20       V21       V22  \
3292    0.063175  0.802281 -0.657507  ... -0.041477  0.048136 -0.056744
26880   0.608729  0.137348 -0.776017  ...  0.092950  0.218024  0.620260
110716  0.072032 -1.436130 -0.533149  ... -0.135218  1.267949 -1.195668
262673  0.452572  0.221266 -0.248835  ... -0.217222 -0.209164 -0.734886
203424 -1.272075 -1.321470  0.292009  ... -0.756527  2.761516  0.497732
...          ...       ...       ...  ...       ...       ...       ...
254395  1.438537 -0.395603 -1.555142  ... -0.206239  0.242560  0.841230
42473  -9.938412  2.830086 -5.659162  ...  1.384743  2.263770  0.620749
114271 -2.614242  1.066636 -1.135497  ...  0.011557  0.528421  0.228027
208651 -3.490350  1.094734 -0.717418  ...  0.357369  0.621622  0.043807
234633 -0.898702  0.123062 -2.748496  ...  0.313332  0.209086 -0.425938

             V23       V24       V25       V26       V27       V28  Amount
3292   -0.218672 -0.339359  0.428465 -0.123194 -0.044684 -0.043321   44.99
26880   0.095627  0.417920 -0.664147 -0.418591  0.318202  0.126036   19.00
110716  0.018153 -1.059279  0.020160  0.148556  0.336041  0.113095    2.68
262673  0.094828 -0.664417 -0.357572  0.261315 -0.242860 -0.039860    1.98
203424  0.181607  0.514103 -0.048922 -0.092722  0.148431  0.093342   24.48
...          ...       ...       ...       ...       ...       ...     ...
254395 -0.370157 -0.026012  0.491954  0.234576 -0.279788 -0.331933    7.59
42473  -0.094069  0.536719  0.398142  0.008277  2.053524  0.835749    3.79
114271 -0.749298 -0.067179  0.215792 -0.453651  0.349191  0.198862   16.48
208651  0.102711 -0.601505  0.127371 -0.163009  0.853792  0.356503   39.45
234633 -0.154440 -0.018820  0.632234  0.192922  0.468181  0.280486    1.59

[800 rows x 30 columns]

In [195]:
print(Y)

3292      0
26880     0
110716    0
262673    0
203424    0
         ..
254395    1
42473     1
114271    1
208651    1
234633    1
Name: Class, Length: 800, dtype: int64

Splitting the Data into Training Data and Test Data

In [196]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.10, stratify = Y, random_state = 2)

In [197]:
print(X.shape,X_train.shape,X_test.shape)

(800, 30) (720, 30) (80, 30)

In [198]:
print(Y.shape,Y_train.shape,Y_test.shape)

(800,) (720,) (80,)

MODEL TRAINING
> Logistical Regression Method

In [199]:
model = LogisticRegression()

In [200]:
# Training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

MODEL EVALUATION

>Accuracy Score

In [201]:
# Accuracy on Training Data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [202]:
#Accuracy is described below
print("Accuracy on Training Data : ", training_data_accuracy)

Accuracy on Training Data :  0.9444444444444444

In [203]:
# Accuracy on Test Data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [204]:
#Accuracy is described below
print("Accuracy on Training Data : ", test_data_accuracy)

Accuracy on Training Data :  0.925